# Site settings
baseurl = "your_site_url_address"
languageCode = "en"
title = "LABEL SERVICES / MANAGEMENT SERVICES"
theme = "hugo-theme-cactus-plus"
googleAnalytics = "your_google_analytics_id"
# Set the value to true if your site include CJK (Chinese, Japanese, and Korean languages) characters
hasCJKLanguage = false

[params]
	author = "LABEL SERVICES / MANAGEMENT SERVICES"
	description = "LABEL SERVICES / MANAGEMENT SERVICES"
	bio = "Maintenace In Progress.   We apologize for the Inconvenience. The site will be available soon."



	enableRSS = true
	enableToc = true

	enableDisqus = true
	disqusShortname = "your_disqus_short_name"


	enableSummary = true
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = false


	enableGoogleAnalytics = true
	enableBaiduAnalytics = false
	# Set the value to your baidu analysis code if you want to use baidu analytics
	baiduAnalytics = 'your_baidu_analysis_code'

	enableTwitterCard = true
	# The url for twitter card image, default is avatar.png in static/images directory
	twitterCardImage = ""

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = "kimchiwine.net"
	about = ""
	archive = ""
	subscribe = ""

	olderPosts = ""
	newerPosts = ""
	copyright = "Â© KIMCHIWINE, 2018"

	# show latest posts in single page
	showLatestPosts = false
	readMore = ""

	# Share
	enableShare = true
	tweet = ""
	share = ""

	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""


